.EE
======================================================================
ERROR: test_list_int (__main__.Test02_AccurateDayCount)
*** Test02 *** Opens JSON File and counts items in list ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stileco_/SchoolStuff/CPSC362/CPSC-362-Automated-Trading-Systems/test.py", line 53, in test_list_int
    with open(dataFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'FNGU_data.json'

======================================================================
ERROR: test_list_int (__main__.Test03_MatchDay)
*** Test03 *** Data is consistent with a given day ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stileco_/SchoolStuff/CPSC362/CPSC-362-Automated-Trading-Systems/test.py", line 65, in test_list_int
    with open(dataFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'FNGU_data.json'

----------------------------------------------------------------------
Ran 3 tests in 0.223s

FAILED (errors=2)
